[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "http://odysex.com/*"
  to = "https://odysex.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.odysex.com/*"
  to = "https://odysex.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.odysex.com/*"
  to = "https://odysex.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://www.odyssey.trade; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"